### PR TITLE
Adds typescript typings

### PR DESCRIPTION
**Pull request by chagasaway**
This adds `typescript` typings to the project which helps the adoption in typescript based projects.

### CODE REVIEW

**Comment by zth** [comment]
This looks good! Would you mind rebasing to master? I've made a few changes and gotten rid of the ExtractId function + the generated lib directory from the repo

**Review by jgcmarins — APPROVED** [review]
nice

**Comment by chagasaway** [comment]
@zth just rebased and updated the typings with master 👍

**Comment by zth** [comment]
Thank you! I'm away for the weekend, but I'll merge this and cut a new release early next week. Thanks for contributing!

**Comment by chagasaway** [comment]
Awesome! Any issue with my changes, or any other improvements that my help would be appreciated, just let me know.

**Comment by zth** [comment]
I think it's great! In an ideal world I'd like to autogenerate the TS bindings from the Flow bindings, but I haven't really found a stable lib for that yet.

I'm very interested in what kinds of issues you run into running this in your projects, and what features you'd want. 

Thanks again!

**Comment by zth** [comment]
Released in `0.9.3`!

**Comment by chagasaway** [comment]
@zth yes, it's something that I will keep watching to find a nice way to keep those types in sync, until that, feel free to assign me to update the types on the next updates!

**Pull request merged**
